### ISSUE TITLE
fix n-1 attack detection so it triggers our mitigation strategy

### ISSUE THREAD

**Issue by david415** [katzenpost/katzenpost#206]
We really ought to be using decoy loops to try and detect n-1 attacks... from the mixes of course. We can use some kind of dumb heuristic like, two missing loop packets in a row triggers the mitigation strategy, which is to stop routing packets.

Technically this is a bug because we've got certain well defined behavior that we haven't implemented. This approaches the definition of a bug.

**Comment by mixmasala** [comment]
should we add a configuration flag so that we can have a permissive / restrictive mode? that is, if we think that the heuristic / mitigration strategy can be used to DOS the network, or be easily triggered by transient faults we may want a way to disable it by configuration.
for example, adding configuration options of the form:
mitigation_threshold = 
mitigration_strategy = "WARN" // "HALT", "NONE"

**Comment by david415** [comment]
i agree the n-1 mitigation needs to be optional or at least the threshold needs to be tunable.
if setup incorrectly, we could accidentally DOS the network with this feature.
warn is useful for tuning.

halt. i wouldn't call it halt, because the mitigation shouldn't actually stop the mix node, just pause the routing for some number of specified minutes. maybe we call it PAUSE instead. but of course the duration would need to be specified.

The configuration settings for this... we might eventually want it to be enforced by dirauth configs/voting because all mix nodes should have the exact same behavior so as not to create an advantage for specific restricted sets of routes.
