### ISSUE TITLE
replace core/queue ASAP!!!

### ISSUE THREAD

**Issue by david415** [katzenpost/katzenpost#212]
NOTE: we use core/queue, our priority queue implementation based on golang's heap package. core/queue is used by every component of katzenpost.

our priority queue does not properly handle duplicate priorities. this can lead to subtle bugs.

possible solutions:

1. write a well tested priority queue from scratch
2. find an existing priority queue in golang, that has the properties we want

Whatever we replace it with, it must be a datastructure that has:

1. O(log n) insertion of entry by priority
2. O(1) pop/deletion of latest priority
3. O(log n) deletion by specified priority
4. it must handle duplicate priorities properly and not loose any data!

**Comment by mixmasala** [comment]
I think we agree that we do not need the ability to remove by priority - I wrote this thinking I needed a mechanism to remove messages from a PriorityQueue that held Messages until they were ACK'd, where the soonest-to-timeout Message is at the front of the PriorityQueue

However, it is much simpler/cheaper to just let the timer fire for each message, and check whether it was ACK'd from a different datastructure. Amusingly, I already did that, so the fix was to just remove calls to RemovePriority.

**Comment by mixmasala** [comment]
Fix merged in #216
