### ISSUE TITLE
Failed to spawn server instance: nonvoting/client: AuthorityIdentityKeyPublicKey is mandatory

### ISSUE THREAD

**Issue by a304640598** [katzenpost/katzenpost#252]
How to modify the katezenpost.toml file to make this error no longer display. I can configure the publickeypem = " " No matter how modified [PKI.Novoting] it is modified in the Toml configuration file, no anymore in the compilement file cfg.PKI.Nonvoting.PublicKey has content, how should I debug

**Comment by david415** [comment]
you could run the makefile in the docker repo and learn about how to properly configure katzenpost from inspecting the output of genconfig. either that or wait until we deploy our new documentation and website.

i'm closing this ticket because there is no action for the dev team to take here.

**Comment by leif** [comment]
The Nonvoting PKI is currently not maintained (and not working) and it might get removed soon rather than being fixed.

To run a containerized testnet with a PKI from voting authorities, you can `cd docker && make start`. You can read `docker/Makefile` to see how this generates all of the config files etc using the `genconfig` tool, and see the other make targets for interacting with your test network.

This should be better documented soon.
