### ISSUE TITLE
build fails: unable to access 'https://git.schwanenlied.me/yawning/aez/'

### ISSUE THREAD

**Issue by tinybeachthor** [katzenpost/katzenpost#31]
While trying to build this project, I get:
```
> fatal: unable to access 'https://git.schwanenlied.me/yawning/aez/': Could not resolve host: git.schwanenlied.me
```

Is the project still maintained? 
If so, could the dependency be moved to github?

**Comment by david415** [comment]
what were you trying to build?
yeah maybe we need to change our dependency import path to use yawning's gitlab repo:
https://gitlab.com/yawning/aez

looks like @yawning's personal git server/web server is not responding.

is the project still maintained?

it depends on what you mean by that more specifically... currently there isn't a volunteer operated mixnet... so i'd say this project hasn't even started yet.

that having been said I'm currently working on making Katzenpost use a Sphinx cryptographic packet format use a generic NIKE interface so that we can have classical sphinx and post quantum sphinx packets flowing through the same network, layering one inside the other to form a hybrid (classical + pq) mixnet protocol to protect the anonymity and privacy notions of the network against active quantum adversaries (which probably don't exist yet but usa, russia and china foaming at the mouth to get there first).

**Comment by david415** [comment]
if you properly report a bug i will fix it. :-)

**Comment by Yawning** [comment]
> looks like @Yawning's personal git server/web server is not responding.

Yeah, as part of reducing the amount of services I have to maintain and host, I moved most of my stuff to github/gitlab.

**Comment by tinybeachthor** [comment]
@david415 
I was trying to build `server` and `authority`, I get the same error on both.

It's not really a bug, just the dependencies are not accessible anymore.

The dependencies:
https://github.com/katzenpost/server/blob/88ff6a87378f0bace49d12824e7a1127aa8640af/go.mod#L6-L8
https://github.com/katzenpost/core/blob/a0ceb0b7f6b15eb17ffd6abc437f795e3a2ad3e7/go.mod#L6-L7
https://github.com/katzenpost/reunion/blob/9d763da2f5037fdd91520105d3a6f350a8b1402d/go.mod#L6

@Yawning 
If you moved these already to a public repo, could you share a link?

**Comment by david415** [comment]
@tinybeachthor those are old historical repos we aren't using anymore. we've moved those old repos into this one.
